# Generated by Django 4.0 on 2022-02-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
